### ISSUE TITLE
use customize for all

### ISSUE THREAD

**Issue by ghost** [emacsorphanage/magit-gerrit#42]
There's already customize group magit-gerrit. Would be nice to be able to set magit-gerrit-remote and magit-gerrit-ssh-creds in there as well.

**Comment by terranpro** [comment]
Though I personally don't use the customize interface, I would be for this except I'm not sure how customs work together with buffer local variables.  I hoped to keep separate gerrit repos as configurable as possible.

For instance, I use `(setq-default magit-gerrit-ssh-creds "me@b.com")` for most of my projects, but for one repo I re-set it to a special "me@c.com" account.

I'll do some checking on this - would love to see how other elisp'ers have handled this scenario.

**Comment by tarsius** [comment]
This package isn't being maintained anymore, so new features won't be added.
