### ISSUE TITLE
expand readme

### ISSUE THREAD

**Issue by ghost** [emacsorphanage/magit-gerrit#43]
Would be nice to explain in more detail on usage (maybe even with pictures :)
It's not immediately clear that 'R P' works in the commit list available via 'l l' and not from magit's status buffer.

**Comment by NimoTh** [comment]
Not only the readme, but also the documentation inside emacs itself. For example, what are the customizable variables for and how do I use them. In particular, is it possible to use magit-gerrit-arguments to filter by a specific branch?

**Comment by tarsius** [comment]
Not what you had mind, but I just added "This package isn't being maintained anymore.", which by now is the most important piece of documentation.
