### ISSUE TITLE
document refspec for pushing

### ISSUE THREAD

**Issue by ghost** [emacsorphanage/magit-gerrit#44]
While trying to push commit to gerrit via R P I've got request for remote branch name.
Pushing via command-line works as follows:
git push gerrit HEAD:refs/for/master
I still can't figure out what to enter as a branch name - trying "for/master" leads to errors for example. Would be nice to configure this name per-repo or globally as well.

**Comment by lanejo01** [comment]
Did you ever figure this out?

**Comment by osmoc** [comment]
Unfortunately not - I have to use "git review" for that instead.

**Comment by terranpro** [comment]
Hi,
If you set your branch to track a remote branch it shouldn't ask you for that when you push a commit for review.

If you don't do this, try hitting 'tab' and it should display a list of possible completions.

I'll update the documentation to make this more clear.  Please let me know if you have any more issues or this didn't work for you.  Thanks!

**Comment by osmoc** [comment]
Unfortunately, it still doesn't work for me:
- setting upstream for branch is incompatible with our workflow (we create through-away topic branches just for pushing for review which are get automatically deleted by "git review -f")
- using tab completion lists all the branches except the one I need

As far as I've understood how gerrit works it's sort of "virtual" branch which hence is not displayed when calling 'y' in magit and thus is unavailable to magit-gerrit's completion.

Having said that, it's most likely possible to somehow set it manually, I've just haven't figured out the way yet. So far using "git review -f" works for me, but the need to switch back and forth is rather annoying. Would be nice if magit-gerrit could just call it (or implement the same functionality somehow).

**Comment by terranpro** [comment]
Just took a quick peek at the git-review man page in the examples section showing `git-review -f`

It looks like `git-review -f` will push to the `master` branch of your remote, cleanup your current, and then switch you back to local `master`.

You can get this same functionality in magit-gerrit just by selecting `master` from the remote branch completions.

Maybe you are actually concerned about the 'topic' and not the remote branch? =)

The format given to git push looks like=>  `refs/for/BRANCH/TOPIC` or `refs/publish/BRANCH/TOPIC` (equivalent IIRC) or for drafts `refs/drafts/BRANCH/TOPIC`

I think in magit-gerrit's `master` branch, the topic is added by default as the name of the local branch.

But in the `next` branch the push popup menu has an option to choose both the topic and the remote branch.  (If so you might be interested in testing out the `next` branch)

I believe the default behavior in magit-gerrit master branch is the same as what you get from `git-review -f`.  I tried `git-review --dry-run -f -v -r origin` locally and it showed:

`git push origin HEAD:refs/publish/master/coolfeature`

You might try this on a test branch and compare the output of magit-process buffer with git-review output - as far as I know only the git push line is relevant.  Hope this helps/makes sense!

**Comment by tarsius** [comment]
Closing this because I have never used this package and cannot help you and there is no proper maintainer anymore who might be able to help.
