### ISSUE TITLE
make timeout configurable

### ISSUE THREAD

**Issue by ghost** [emacsorphanage/magit-gerrit#45]
If gerrit server is down (java, doh!) thna running magit with gerrit extension takes considerable time. Would be nice to make whatever timeout is there configurable via customize so users can quicker figure out that gerrit is dead and just go on without it.

**Comment by terranpro** [comment]
Hi!  Thanks for the recent interest and feedback =)
This is a great idea, and though I've only experienced it once or twice, when it does happen you are right that it is painful to wait with emacs locked up for magit-status to refresh

It looks like this can be accomplished by adding the option `ConnectTimeout` when invoking ssh

**Comment by osmoc** [comment]
Cool. Is there a way to test it using MELPA or some other package?

**Comment by tarsius** [comment]
If you want this merged, then open a pull-request.
