### ISSUE TITLE
Tag release 0.4

### ISSUE THREAD

**Issue by mnuessler** [emacsorphanage/magit-gerrit#51]
The last release 0.3 is from 2015. Since then, a couple of fixes have been merged into the master. Please tag a new release, so that it can be installed from MELPA Stable.

**Comment by osmoc** [comment]
Would be nice indeed. There seems to be sort of dependency problem as well which should be checked for before tagging release - see #54 for details.

**Comment by tarsius** [comment]
I have added a tag. Since I haven't used this package or (gerrit itself) even just once, I don't know whether this tags a functioning version.
