### ISSUE TITLE
magit-insert-gerrit-reviews: Symbol’s value as variable is void: cl-struct-magit-section-tags

### ISSUE THREAD

**Issue by ghost** [emacsorphanage/magit-gerrit#54]
The magit-gerrit started failing recently with this error:
`magit-insert-gerrit-reviews: Symbol’s value as variable is void: cl-struct-magit-section-tags`
Emacs 25.3.2, magit-gerrit 20160226.130, magit 20180212.1622

**Comment by osmoc** [comment]
Note:   cl-lib 0.6.1 is installed.

**Comment by dholm** [comment]
I think this is because in 651a9abccaf7ba8336bb5fbef32fde88043cf9aa Magit switched from using `cl-struct` to an `eieio` class for `magit-section`.

**Comment by dholm** [comment]
I deleted `magit-gerrit`, restarted Emacs and then reinstalled it again and now it works fine.  I guess the byte-compiled version included the now obselete `cl-struct-magit-section-tags`.

**Comment by tarsius** [comment]
Yes most likely that was the problem.
