### ISSUE TITLE
Unable to use magit-gerrit with recent magit

### ISSUE THREAD

**Issue by AmCrNi** [emacsorphanage/magit-gerrit#55]
Compiling magit-gerrit shows:
`
magit-gerrit.el:596:1:Warning: the following functions are not known to be defined:
    magit-section-hidden, magit-section-type, magit-section-value
`
Pressing R W on git repository gives:
`magit-gerrit-push-review: Symbol’s function definition is void: magit-section-type`

Enabling debug-on-error:

`Debugger entered--Lisp error: (void-function magit-section-type)
  magit-section-type(#<magit-section magit-section>)
  magit-gerrit-push-review(drafts)
  magit-gerrit-create-draft()
  funcall-interactively(magit-gerrit-create-draft)
  #<subr call-interactively>(magit-gerrit-create-draft)
  apply(#<subr call-interactively> magit-gerrit-create-draft nil)
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> magit-gerrit-create-draft)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> magit-gerrit-create-draft)
  call-interactively(magit-gerrit-create-draft)
  magit-invoke-popup-action(87)
  funcall-interactively(magit-invoke-popup-action 87)
  #<subr call-interactively>(magit-invoke-popup-action nil nil)
  apply(#<subr call-interactively> magit-invoke-popup-action (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> magit-invoke-popup-action nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (magit-invoke-popup-action nil nil))
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)`

Magit 20180616.1530, Git 2.16.4, Emacs 26.1, gnu/linux
magit-popup        20180509.1041
magit-gerrit       20160226.130

**Comment by SavchenkoValeriy** [comment]
I've encountered exactly the same issue

**Comment by SavchenkoValeriy** [comment]
According to this commit
https://github.com/magit/magit/commit/3f3bc14f32aa02cbfd5270ba93af3cfd99e73704#diff-b53020af014cb198e7207b81fb113ea8
these functions have been obsolete for quite some time.

I can suggest making an ad-hoc fix replacing the calls with `(oref $SECTION $FIELD)`

**Comment by SavchenkoValeriy** [comment]
https://github.com/terranpro/magit-gerrit/pull/56 seems to address this issue (partially at least).

**Comment by AmCrNi** [comment]
`
--- magit-gerrit.el     2018-06-21 18:09:41.287594313 +0200
+++ magit-gerrit/magit-gerrit.el        2018-06-21 18:10:29.532185118 +0200
@@ -4,7 +4,6 @@
 ;;
 ;; Author: Brian Fransioli <assem@terranpro.org>
 ;; URL: https://github.com/terranpro/magit-gerrit
-;; Package-Version: 20160226.130
 ;; Package-Requires: ((magit "2.3.1"))
 ;;
 ;; This program is free software; you can redistribute it and/or
@@ -249,7 +248,7 @@
                 (magit-gerrit-pretty-print-review num subj owner-name isdraft)
                 'magit-gerrit-jobj
                 jobj))
-       (unless (oref (magit-current-section) hidden)
+       (unless (magit-section-hidden (magit-current-section))
          (magit-gerrit-wash-approvals approvs))
        (add-text-properties beg (point) (list 'magit-gerrit-jobj jobj)))
       t)))
@@ -401,9 +400,9 @@
 (defun magit-gerrit-push-review (status)
   (let* ((branch (or (magit-get-current-branch)
                     (error "Don't push a detached head.  That's gross")))
-        (commitid (or (when (eq (oref (magit-current-section) type)
+        (commitid (or (when (eq (magit-section-type (magit-current-section))
                                 'commit)
-                        (oref (magit-current-section) value))
+                        (magit-section-value (magit-current-section)))
                       (error "Couldn't find a commit at point")))
         (rev (magit-rev-parse (or commitid
                                   (error "Select a commit for review"))))
`
This patch worked for me.

**Comment by xeonxu** [comment]
@AmCrNi Send PR plz. This patch worked for me too.

**Comment by tarsius** [comment]
I have merged something similar a while ago.
